// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://claikrivacqpygpohzzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNsYWlrcml2YWNxcHlncG9oenpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2ODA2OTIsImV4cCI6MjA1NTI1NjY5Mn0.o76WuJHIYKZhN_HfE-5eSxvTTC9hgYLyWF6CAe-EFvk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);